# Rclone RC Web GUI Configuration

# TODO: Same as below
# FIXME: Decide on a parameter set!!!

# These override the built-in defaults from the systemd unit
# RC_PORT=5572        # Default web GUI port
# RC_ADDR=127.0.0.1   # Default bind address
