# [Service]

# Environment="RC_FLAGS=--rc-user=admin --rc-pass=admin" # Can't be used due to multiple unresolved login issues. Please use a reverse proxy with login and redirect if need to expose this service to public web.
# Environment="RC_FLAGS=--rc-no-auth"

