# Rclone Bisync service config

# TODO: Same as below
# FIXME: Decide on a parameter set!!!

# These override the built-in defaults from the systemd unit

# SYNC_ROOT=~/.rclone-bisync                        # Default sync root directory
# BISYNC_FLAGS=""                                   # Additional bisync flags
# CHECK_FILE="RCLONE_TEST"                          # Default check filename
# REMOTE=DefaultRemote:                             # RClone Remote identifier. Always pass `:` in RClone expected format!
# CACHE_DIR=/var/cache/rclone-bisync/DefaultRemote  # Caches if directory was initialized for bisync
# LOCAL_PATH=~/.rclone-bisync/DefaultRemote         # Path storing remote files locally

