# Rclone Bisync service config

# TODO: Same as below
# FIXME: Decide on a parameter set!!!

# These override the built-in defaults from the systemd unit
# SYNC_ROOT="%h/Sync"          # Default sync root directory
# LOCK_TIMEOUT=1800            # Default lock timeout in seconds
# BISYNC_FLAGS=""              # Additional bisync flags
# CHECK_FILE="RCLONE_TEST"     # Default check filename
