# Required
SYNC_ROOT="$HOME/Sync"

# Optional
LOCK_TIMEOUT=1800
BISYNC_FLAGS=""

# 
REMOTE="$1"
LOCAL_BASE="${RCLONE_BISYNC_BASE:-$HOME/Sync}"
LOCAL_PATH="$LOCAL_BASE/$REMOTE"
CACHE_DIR="$LOCAL_BASE/.rclone-bisync/$REMOTE"
CHECK_FILE="RCLONE_TEST"
