# [Service]

# Override service defaults per-instance.
# Copy to: ~/.config/systemd/user/rclone-bisync@.service.d/override.conf
# or per-instance: ~/.config/systemd/user/rclone-bisync@MyRemote.service.d/override.conf

# Environment="BISYNC_FLAGS=--verbose"
# Environment="LOCAL_PATH=/mnt/data/MyRemote"
# Environment="CHECK_FILE=RCLONE_TEST"
